name: notification

services:
    postgres:
        image: postgres:17-alpine
        container_name: notification-postgres

        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: notificationpassword
            POSTGRES_DB: notification_service_db

        ports:
            - '5436:5432'

        volumes:
            - notification_postgres_data:/var/lib/postgresql/data

        healthcheck:
            test:
                [
                    'CMD-SHELL',
                    'pg_isready -U postgres -d notification_service_db',
                ]
            interval: 5s
            timeout: 5s
            retries: 5

        restart: unless-stopped

volumes:
    notification_postgres_data:
