name: booking

services:
  postgres:
    image: postgres:17-alpine
    container_name: booking-postgres

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: bookingpassword
      POSTGRES_DB: booking_service_db

    ports:
      - "5434:5432"

    volumes:
      - booking_postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d booking_service_db"]
      interval: 5s
      timeout: 5s
      retries: 5

    restart: unless-stopped

volumes:
  booking_postgres_data: